### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by auvipy** [python-bangladesh/website#1]
A read me with different instructions will be great.

**Comment by masnun** [comment]
Good idea, will do soon. Currently too focused on making the site usable.

**Comment by fa7ad** [comment]
Any updates? I want to contribute, but without a README... I'm lost :worried:

**Comment by masnun** [comment]
I will start a new project from scratch. Please give me a day or two. Will do.

**Comment by fa7ad** [comment]
Is there a solid reason behind using Python for the website? wouldn't github-pages be easier to deal with (+ no hosting :smile: )?

**Comment by masnun** [comment]
dynamic content

**Comment by fa7ad** [comment]
Anything specific in mind?

**Comment by masnun** [comment]
member profiles. 

besides the app is supposed to be a collaborative learning experience for beginners.

**Comment by fa7ad** [comment]
Okay, sounds good to me

**Comment by excalliburbd** [comment]
Any updates on this?

**Comment by masnun** [comment]
https://github.com/python-bangladesh/pybd.org
