### ISSUE TITLE
DEBUG is enabled

### ISSUE THREAD

**Issue by shantanu404** [python-bangladesh/website#5]
Looks like `DEBUG=True` is enabled. Even in production :-1:  That should not happen :disappointed: 
The page stated in #3 is showing this error at the bottom of the page
`You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.`

**Comment by excalliburbd** [comment]
Hi @shantanu69. You are right! Debug should not be enabled.

I am sure you realize that the new website is being developed [here](https://github.com/python-bangladesh/pybd.org). We will try to remember to turn debug off before pushing to production. Thanks!

**Comment by shantanu404** [comment]
Oh! Sorry and thanks for the reply :smile:
